// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp35xiFWc6ufdoHb297glcP0V5aFLrJ7s',
    appId: '1:1088610447610:web:5f257410256fd935e29943',
    messagingSenderId: '1088610447610',
    projectId: 'music-f1684',
    authDomain: 'music-f1684.firebaseapp.com',
    storageBucket: 'music-f1684.appspot.com',
    measurementId: 'G-D06MWKDH88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQxsrZIjRrU0R-fwOeLUCEJwEk6hwZqcQ',
    appId: '1:1088610447610:android:76c2e669d3964200e29943',
    messagingSenderId: '1088610447610',
    projectId: 'music-f1684',
    storageBucket: 'music-f1684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkySwKgNBy8cY0ueFGxy9m14aJ-X63ls',
    appId: '1:1088610447610:ios:a46e013c0d855817e29943',
    messagingSenderId: '1088610447610',
    projectId: 'music-f1684',
    storageBucket: 'music-f1684.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFkySwKgNBy8cY0ueFGxy9m14aJ-X63ls',
    appId: '1:1088610447610:ios:c809d05a6c29446be29943',
    messagingSenderId: '1088610447610',
    projectId: 'music-f1684',
    storageBucket: 'music-f1684.appspot.com',
    iosBundleId: 'com.example.untitled2.RunnerTests',
  );
}
